# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca1775e274303d4d175d16057fd635d6"
name = "Doorships.in"
application_url = "https://shopify-connector-door-ships.vercel.app"
embedded = true

[access_scopes]
scopes = "read_locations,read_orders,read_markets_home,write_orders,read_inventory,read_fulfillments,write_fulfillments,write_products,write_metaobjects,write_metaobject_definitions,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,read_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"
  
  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks/orders/updated"
  
  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks/orders_cancelled"
  
  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app_uninstalled"
  
  [[webhooks.subscriptions]]
  topics = ["fulfillments/create"]
  uri = "/webhooks/fulfillments_create"
  
  [[webhooks.subscriptions]]
  topics = ["fulfillments/update"]
  uri = "/webhooks/fulfillments_update"


[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
